# load data

In [1]:
# load train data
import numpy as np  
import pandas as pd
import matplotlib.pyplot as plt

TRAIN_DATA = '../temp/2024年四川省大学生数据科学与统计建模竞赛/训练集/train_data.csv'
TRAIN_TARGET = '../temp/2024年四川省大学生数据科学与统计建模竞赛/训练集/train_target.csv'

train_data = pd.read_csv(TRAIN_DATA)
train_target = pd.read_csv(TRAIN_TARGET)

In [2]:
train_data.shape, train_target.shape

((61866, 3807), (61866, 3))

In [3]:
train_data.iloc[0:5, 0:5]

   idx        X0        X1        X2  X3
0    0  0.990494  0.414321  0.107851 NaN
1    1  0.990494  0.414321  0.290702 NaN
2    2  0.884800  0.115568  0.100987 NaN
3    3  0.523825  0.115568  0.980636 NaN
4    4  0.884800  0.698709  0.740793 NaN

In [4]:
train_data.iloc[0:5, 200:210]

,X199,X200,X201,X202,X203,X204,X205,X206,X207,X208
0,0.037831,0.143533,0.422436,0.131286,0.637511,0.909085,0.519160,0.267959,0.785438,0.782341
1,0.930105,0.190699,0.658183,NaN,0.263675,0.949974,0.027025,0.032785,0.306463,0.306658
2,0.940351,0.179949,0.390476,NaN,0.263675,0.994614,0.347510,0.310275,0.306463,0.306658
3,0.641123,0.920604,NaN,NaN,0.263675,0.986879,0.256141,0.808868,0.928007,0.922778
4,0.880082,0.645542,0.857562,0.610858,0.972198,0.578989,0.725978,0.558131,0.928007,0.922778

In [5]:
train_target.head(5)

   idx  date    y
0    0     7  0.0
1    1     7  0.0
2    2     8  0.0
3    3     7  0.0
4    4     7  0.0

# None value

In [6]:
train_data.drop(['idx'], axis=1, inplace=True)
train_data.loc[3, 'X201']

nan

In [7]:
train_data.isna().sum()

X0           0
X1        2301
X2       10899
X3       56763
X4       52321
         ...
X3801    51382
X3802    51382
X3803    51382
X3804    51382
X3805    51382
Length: 3806, dtype: int64

In [8]:
train_data_fillna = train_data.fillna(train_data.mean())
train_data_fillna.loc[3, 'X201']

0.5029270735953963

In [9]:
train_data_fillna.isna().sum()[train_data_fillna.isna().sum() != 0]

X294     61866
X410     61866
X629     61866
X661     61866
X685     61866
         ...
X3477    61866
X3478    61866
X3591    61866
X3602    61866
X3613    61866
Length: 111, dtype: int64

In [10]:
train_data_fillna_drop = train_data_fillna.dropna(axis=1)
train_data_fillna_drop.shape, train_data.shape

((61866, 3695), (61866, 3806))

## normalization

In [11]:
train_data_fillna.head(5)

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X3796,X3797,X3798,X3799,X3800,X3801,X3802,X3803,X3804,X3805
0,0.990494,0.414321,0.107851,0.500568,0.500187,0.499641,0.225406,0.059681,0.093200,0.166164,...,0.523254,0.521925,0.494501,0.495557,0.494208,0.494231,0.495263,0.495317,0.493827,0.493676
1,0.990494,0.414321,0.290702,0.500568,0.500187,0.499641,0.500624,0.120044,0.163581,0.166164,...,0.214184,0.214184,0.958319,0.795370,0.841912,0.919290,0.835351,0.774155,0.736554,0.765282
2,0.884800,0.115568,0.100987,0.500568,0.500187,0.499641,0.500624,0.016119,0.059394,0.013176,...,0.523254,0.521925,0.494501,0.495557,0.494208,0.494231,0.495263,0.495317,0.493827,0.493676
3,0.523825,0.115568,0.980636,0.500568,0.500187,0.499641,0.500624,0.059681,0.029519,0.166164,...,0.523254,0.521925,0.494501,0.495557,0.494208,0.494231,0.495263,0.495317,0.493827,0.493676
4,0.884800,0.698709,0.740793,0.500568,0.753101,0.499641,0.758504,0.662325,0.784138,0.979358,...,0.523254,0.521925,0.494501,0.495557,0.494208,0.494231,0.495263,0.495317,0.493827,0.493676

In [12]:
train_data_fillna_drop_norm = (train_data_fillna_drop - train_data_fillna_drop.mean()) / train_data_fillna_drop.std()
train_data_fillna_drop_norm.head(5)

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X3796,X3797,X3798,X3799,X3800,X3801,X3802,X3803,X3804,X3805
0,1.709604,-0.364987,-1.562489,0.0,9.770206e-16,1.243610e-15,-2.221561e+00,-1.618875,-1.514485,-1.218867,...,1.956724e-15,0.000000,5.428685e-16,0.000000,-1.630523e-15,-1.087010e-15,-1.621701e-15,1.620792e-15,-1.089747e-15,-1.104692e-15
1,1.709604,-0.364987,-0.859708,0.0,9.770206e-16,1.243610e-15,8.961731e-16,-1.406030,-1.266209,-1.218867,...,-2.723617e+00,-2.784325,4.535885e+00,2.914316,3.404360e+00,4.161721e+00,3.311772e+00,2.713803e+00,2.382499e+00,2.702521e+00
2,1.333118,-1.432679,-1.588871,0.0,9.770206e-16,1.243610e-15,8.961731e-16,-1.772480,-1.633739,-1.762651,...,1.956724e-15,0.000000,5.428685e-16,0.000000,-1.630523e-15,-1.087010e-15,-1.621701e-15,1.620792e-15,-1.089747e-15,-1.104692e-15
3,0.047310,-1.432679,1.792027,0.0,9.770206e-16,1.243610e-15,8.961731e-16,-1.618875,-1.739126,-1.218867,...,1.956724e-15,0.000000,5.428685e-16,0.000000,-1.630523e-15,-1.087010e-15,-1.621701e-15,1.620792e-15,-1.089747e-15,-1.104692e-15
4,1.333118,0.651364,0.870198,0.0,2.225699e+00,1.243610e-15,2.081612e+00,0.506110,0.922857,1.671572,...,1.956724e-15,0.000000,5.428685e-16,0.000000,-1.630523e-15,-1.087010e-15,-1.621701e-15,1.620792e-15,-1.089747e-15,-1.104692e-15

## test data

In [13]:
test_data = pd.read_csv('../temp/2024年四川省大学生数据科学与统计建模竞赛/测试集/test_data.csv')

In [15]:
test_data.drop(['idx'], axis=1, inplace=True)
test_data.shape

(18134, 3806)

In [28]:
# Fill Non values with the mean of `train_data`
# and normalize with the mean and std of train_data
test_data_fillna = test_data.fillna(train_data.mean())
test_data_fillna_drop = test_data_fillna.dropna(axis=1)
test_data_fillna_drop_norm = (test_data_fillna_drop - train_data_fillna_drop.mean()) / train_data_fillna_drop.std()
test_data_fillna_drop_norm.head(5)

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X3796,X3797,X3798,X3799,X3800,X3801,X3802,X3803,X3804,X3805
0,-1.450864,-1.432679,-0.020007,0.0,9.770206e-16,1.243610e-15,8.961731e-16,-0.711873,0.503163,1.463917,...,1.956724e-15,0.000000,5.428685e-16,0.000000,-1.630523e-15,-1.087010e-15,-1.621701e-15,1.620792e-15,-1.089747e-15,-1.104692e-15
1,0.047310,1.381808,0.155341,0.0,9.770206e-16,1.243610e-15,8.961731e-16,1.521253,1.613779,1.189941,...,1.956724e-15,0.000000,5.428685e-16,0.000000,-1.630523e-15,-1.087010e-15,-1.621701e-15,1.620792e-15,-1.089747e-15,-1.104692e-15
2,-1.450864,0.797930,0.158208,0.0,9.770206e-16,1.243610e-15,8.961731e-16,-0.111994,-0.207470,-0.235015,...,1.956724e-15,0.000000,5.428685e-16,0.000000,-1.630523e-15,-1.087010e-15,-1.621701e-15,1.620792e-15,-1.089747e-15,-1.104692e-15
3,-0.674338,0.651364,0.206685,0.0,1.854414e+00,1.243610e-15,1.758617e+00,1.324474,1.597045,-1.218867,...,2.350631e+00,3.040309,-1.754894e+00,-1.754578,-1.754087e+00,-1.754306e+00,-1.754869e+00,-1.754412e+00,-1.754761e+00,-1.777325e+00
4,-1.450864,1.600078,1.710768,0.0,9.770206e-16,1.243610e-15,8.961731e-16,1.435370,1.369318,-1.218867,...,1.956724e-15,0.000000,5.428685e-16,0.000000,-1.630523e-15,-1.087010e-15,-1.621701e-15,1.620792e-15,-1.089747e-15,-1.104692e-15

In [24]:
a = test_data_fillna.isna().sum()[test_data_fillna.isna().sum() != 0].index
b = train_data_fillna.isna().sum()[train_data_fillna.isna().sum() != 0].index
a.values == b.values

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

## export data to csv

In [29]:
# export train_data_fillna_drop_norm
train_data_fillna_drop_norm.to_csv('../dataset/train_data_fillna_drop_norm.csv', index=False)

In [30]:
# export test_data_fillna_drop_norm
test_data_fillna_drop_norm.to_csv('../dataset/test_data_fillna_drop_norm.csv', index=False)

# PCA

In [11]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [12]:
from torchvision import transforms


def pca_lowrank(input: pd.DataFrame, proportion: float) -> torch.tensor:
    # Convert pandas DataFrame to torch tensor
    input_tensor = torch.tensor(input.values, dtype=torch.float32)

    # Normalize the data
    mean = torch.mean(input_tensor, dim=0)
    std = torch.std(input_tensor, dim=0)
    std[std == 0] = 1e-3 # Avoid division by zero
    input_normalized = (input_tensor - mean) / std

    # Calculate the number of principal components based on the proportion of variance to retain
    U, S, V = torch.pca_lowrank(input_normalized)
    total_variance = torch.sum(S**2)
    variance_retained = 0.0
    num_components = 0

    for i in range(len(S)):
        variance_retained += S[i]**2
        num_components += 1
        if variance_retained / total_variance >= proportion:
            break

    # Apply PCA with the calculated number of components
    train_data_pca = torch.matmul(input_normalized, V[:, :num_components])

    return train_data_pca

In [13]:
train_data_pca = pca_lowrank(train_data_fillna, 0.99)
train_data_pca.shape

torch.Size([61866, 6])

In [14]:
# Assuming batch_num, batch_size, and len are defined
batch_size = 50  # Example value
batch_num = train_data_pca.shape[0] // batch_size
length = train_data_pca.shape[1]  # This should be the same as the number of principal components

# Reshape train_data_pca
train_data_pca_reshaped = train_data_pca[:batch_size*batch_num].view(batch_num, batch_size, length)
train_data_pca_reshaped.shape

torch.Size([1237, 50, 6])

In [15]:
train_target.head()

   idx  date    y
0    0     7  0.0
1    1     7  0.0
2    2     8  0.0
3    3     7  0.0
4    4     7  0.0

In [16]:
train_target_drop = train_target.drop(['idx', 'date'], axis=1)
train_target_drop = torch.tensor(train_target_drop.values, dtype=torch.float32)
train_target_drop = train_target_drop[:batch_num*batch_size].view(batch_num, batch_size, -1)
train_target_drop.shape

torch.Size([1237, 50, 1])

# MLP

In [25]:
class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size, bias=True)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size, bias=True)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(output_size, 1, bias=True)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.fc3(x)
        x = self.sigmoid(x)
        return x

In [42]:
from sklearn.metrics import f1_score, auc, roc_curve


class Train:
    def __init__(self, model, criterion, optimizer, batch_size):
        self.model = model
        self.criterion = criterion
        self.optimizer = optimizer
        self.batch_size = batch_size

    def train(self, train_data, train_target, epochs):

        for epoch in range(epochs):
            loss_total = 0
            accuracy_total = 0
            total = 0
            all_preds = np.array([])
            all_labels = np.array([])
            for i in range(train_data.shape[0]):
                self.optimizer.zero_grad()
                output = self.model(train_data[i])
                loss = self.criterion(output, train_target[i])
                loss.backward()
                self.optimizer.step()
                # compute the accuracy
                loss_total += loss.item()
                total += train_target[i].shape[0]
                accuracy_total += torch.sum(
                    (
                        (torch.round(output.detach()) - train_target[i]).abs() < 1e-3
                    ).int()
                ).item()
                # compute the F1 score, AUC, and ROC curve
                all_preds = np.concatenate(
                    [all_preds, torch.round(output.detach()).numpy().flatten()]
                )
                all_labels = np.concatenate([all_labels, train_target[i].numpy().flatten()])
            print(
                f"Epoch {epoch + 1}, Loss: {loss_total}, Accuracy: {accuracy_total / total}," +
                f"F1 Score: {f1_score(all_labels, all_preds)}"
            )

In [44]:
mlp = MLP(input_size=train_data_pca.shape[1], hidden_size=32, output_size=16)
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(mlp.parameters(), lr=0.01)
trainer = Train(model=mlp, criterion=criterion, optimizer=optimizer, batch_size=batch_size)
trainer.train(train_data_pca_reshaped, train_target_drop, epochs=10)

Epoch 1, Loss: 586.7902731001377, Accuracy: 0.816410670978173,F1 Score: 0.0005281225244256667
Epoch 2, Loss: 584.3880375027657, Accuracy: 0.8166531932093776,F1 Score: 0.0
Epoch 3, Loss: 584.7328617572784, Accuracy: 0.8166208569118836,F1 Score: 0.0010568962480183195
Epoch 4, Loss: 584.8699105083942, Accuracy: 0.8166531932093776,F1 Score: 0.0
Epoch 5, Loss: 584.6194954812527, Accuracy: 0.8166531932093776,F1 Score: 0.0
Epoch 6, Loss: 584.5637984275818, Accuracy: 0.8166531932093776,F1 Score: 0.0
Epoch 7, Loss: 584.4943297207355, Accuracy: 0.8166531932093776,F1 Score: 0.0
Epoch 8, Loss: 584.8655266314745, Accuracy: 0.8166531932093776,F1 Score: 0.0
Epoch 9, Loss: 584.6571044623852, Accuracy: 0.8166531932093776,F1 Score: 0.0
Epoch 10, Loss: 585.0776767730713, Accuracy: 0.8166531932093776,F1 Score: 0.0

# XGBoost

In [51]:
train_target_xgb = train_target.drop(['idx', 'date'], axis=1)
train_data.head(5)

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X3796,X3797,X3798,X3799,X3800,X3801,X3802,X3803,X3804,X3805
0,0.990494,0.414321,0.107851,NaN,NaN,NaN,0.225406,0.059681,0.093200,0.166164,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.990494,0.414321,0.290702,NaN,NaN,NaN,NaN,0.120044,0.163581,0.166164,...,0.214184,0.214184,0.958319,0.79537,0.841912,0.91929,0.835351,0.774155,0.736554,0.765282
2,0.884800,0.115568,0.100987,NaN,NaN,NaN,NaN,0.016119,0.059394,0.013176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.523825,0.115568,0.980636,NaN,NaN,NaN,NaN,0.059681,0.029519,0.166164,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.884800,0.698709,0.740793,NaN,0.753101,NaN,0.758504,0.662325,0.784138,0.979358,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
train_target_xgb.shape, train_data.shape

((61866, 1), (61866, 3806))

In [53]:
np.unique(train_target_xgb)

array([0., 1.])

In [55]:
from xgboost import XGBClassifier
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, auc, roc_curve

X_train, X_test, y_train, y_test = train_test_split(train_data, train_target_xgb, test_size=0.2, random_state=42)

model = XGBClassifier(n_estimators=100)
model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)

KeyboardInterrupt: